In [5]:
import numpy as np
import matplotlib.pyplot as plt

# Load train and test data
train_data = np.load('train.npy')  # Load first three samples from train.npy
testlabels= np.load('trainlabels.npy')    # Load first three samples from test.npy
trainlabels=np.load('testlabels.npy')

print(testlabels.shape)
print(train_data.shape)
print(trainlabels.shape)
print(trainlabels[1:])

(30, 4096)
(4096, 20)
(4096, 20)
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [4]:
import numpy as np

# Load the new_labels.npy file
new_labels = np.load('trainlabels.npy')

# Iterate through each column in the new_labels array
for i in range(0,10):
    if np.any(new_labels[i].T == 1):
        print('signal')
    else:
        print('no signal')
print(new_labels.shape)


signal
no signal
no signal
signal
no signal
signal
no signal
no signal
signal
no signal
(30, 4096)
