In [3]:
import numpy as np
import matplotlib.pyplot as plt

# Load train and test data
train_data = np.load('train.npy')  # Load first three samples from train.npy
testlabels= np.load('labels.npy')    # Load first three samples from test.npy
trainlabels=np.load('testlabels.npy')
coinlabels=np.load('coinlabels.npy')

print(testlabels.shape)
print(train_data.shape)
print(trainlabels.shape)
print(trainlabels[1:])

(4096, 20)
(4096, 20)
(4096, 20)
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [5]:
print(coinlabels)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
